# -*- coding: utf-8 -*-
"""funpublicos_caja.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DylQt-reeTBRCnknP_v1k3TI59aiOPL5
"""



"""# Tarea

Descargar los datos CSV de **diciembre de 2025** como `funpub_2025_12.csv` y los archivos históricos de **diciembre** desde **2015 hasta 2024** como `funpub_YYYY_12.csv`, desde `https://datos.sfp.gov.py/data/funcionarios_YYYY_MM.csv.zip`, guardando todos los CSV extraídos en `/content/drive/MyDrive/FUNPUBLICOS/` y luego **verificar la presencia** de todos los archivos de diciembre descargados.

## Definir función de descarga y guardado

### Subtarea

Crear una función en **Python** que reciba como entrada un **año** y un **mes**, construya la URL de descarga del archivo ZIP (por ejemplo, `https://datos.sfp.gov.py/data/funcionarios_YYYY_MM.csv.zip`), lo descargue, extraiga el **CSV** y lo guarde en:

`/content/drive/MyDrive/FUNPUBLICOS/`

con el nombre:

`funpub_YYYY_MM.csv`

La función debe incluir **manejo robusto de errores** (validación de parámetros, control de HTTP, verificación de contenido ZIP, extracción segura, y validación mínima del CSV resultante).
"""

import requests
import zipfile
import os
import io

def download_and_save_csv(year, month):
    """
    Downloads a ZIP file containing a CSV for a given year and month,
    extracts the CSV, and saves it to a specified directory.

    Args:
        year (int): The year of the data (e.g., 2023).
        month (int): The month of the data (1-12).
    """
    # 1. Construct the download URL
    url = f'https://datos.sfp.gov.py/data/funcionarios_{year}_{month:02d}.csv.zip'

    # 2. Define the target directory and ensure it exists
    output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
    os.makedirs(output_dir, exist_ok=True)

    # 3. Define the output CSV filename
    output_filename = f'funpub_{year}_{month:02d}.csv'
    output_filepath = os.path.join(output_dir, output_filename)

    print(f"Attempting to download from: {url}")
    print(f"Target save path: {output_filepath}")

    try:
        # a. Send an HTTP GET request
        response = requests.get(url, stream=True)
        response.raise_for_status()  # Raise HTTPError for bad responses (4xx or 5xx)

        # b. Create a ZipFile object from the content of the downloaded response
        with zipfile.ZipFile(io.BytesIO(response.content)) as zip_file:
            # c. Extract the CSV file from the ZIP archive
            # The CSV filename inside the ZIP is expected to be 'funcionarios_YYYY_MM.csv'
            csv_filename_in_zip = f'funcionarios_{year}_{month:02d}.csv'

            if csv_filename_in_zip not in zip_file.namelist():
                raise KeyError(f"CSV file '{csv_filename_in_zip}' not found in the ZIP archive. Available files: {zip_file.namelist()}")

            # d. Read the content of the CSV and save it to the target directory
            with open(output_filepath, 'wb') as f:
                f.write(zip_file.read(csv_filename_in_zip))

        print(f"Successfully downloaded and saved {output_filename} to {output_dir}")

    except requests.exceptions.RequestException as e:
        print(f"Error during HTTP request for {year}-{month:02d}: {e}")
    except zipfile.BadZipFile as e:
        print(f"Error: The downloaded file for {year}-{month:02d} is not a valid ZIP file. {e}")
    except KeyError as e:
        print(f"Error: {e} in ZIP file for {year}-{month:02d}.")
    except Exception as e:
        print(f"An unexpected error occurred for {year}-{month:02d}: {e}")

print("The `download_and_save_csv` function has been defined.")

"""## Download and Save funpub_2025_12.csv

### Subtask:
Use the defined function to download and save the CSV for December 2025 as `funpub_2025_12.csv`.

**Reasoning**:
The subtask is to download and save the CSV for December 2025. I will call the previously defined `download_and_save_csv` function with the specified year and month.
"""

download_and_save_csv(year=2025, month=12)

"""## Download and Save Historical December Files

### Subtask:
Iterate through a range of years (e.g., 2015 to 2024, based on typical data availability) and use the defined function to download and save the CSV files for December of each year. The filenames will follow the `funpub_YYYY_12.csv` pattern.

**Reasoning**:
The subtask requires iterating through years 2015 to 2024 and downloading the December CSV for each using the previously defined `download_and_save_csv` function.
"""

for year in range(2015, 2025):
    download_and_save_csv(year=year, month=12)

"""# Task
Summarize the verification of the downloaded and existing December files, confirming their presence and adherence to the naming convention in `/content/drive/MyDrive/FUNPUBLICOS/` for files matching the pattern `funpub_*-12.csv`.

## Verify All Downloaded December Files

### Subtask:
List all files in the target directory (`/content/drive/MyDrive/FUNPUBLICOS/`) that match the pattern `funpub_*-12.csv` to confirm that all specified December files (2015-2025) are present with the correct naming convention.

**Reasoning**:
To verify the presence of all downloaded December files, I will list all files in the target directory, generate a list of expected files, and then compare the two lists to identify any missing files.
"""

import os

# 1. Define the output_dir variable
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'

# 2. Create a list of all expected filenames
expected_files = []
for year in range(2015, 2026): # 2015 to 2025 inclusive
    expected_files.append(f'funpub_{year}_12.csv')

print(f"Expected files: {len(expected_files)} files\n{expected_files}\n")

# 3. List all files present in the output_dir
if not os.path.exists(output_dir):
    print(f"Error: Directory '{output_dir}' does not exist.")
    found_files = []
else:
    all_files_in_dir = os.listdir(output_dir)

    # 4. Filter the listed files to identify those that match the pattern
    found_files = []
    for filename in all_files_in_dir:
        if filename.startswith('funpub_') and filename.endswith('_12.csv'):
            # Extract year from filename to check if it's within the range
            try:
                year_str = filename.split('_')[1]
                if year_str.isdigit() and 2015 <= int(year_str) <= 2025:
                    found_files.append(filename)
            except IndexError:
                continue # Skip files that don't match the expected naming convention

print(f"Found files in directory: {len(found_files)} files\n{found_files}\n")

# 5. Compare the set of found files with the set of expected files
set_expected = set(expected_files)
set_found = set(found_files)

missing_files = set_expected - set_found
present_files = set_expected.intersection(set_found)

if not missing_files:
    print("Verification successful: All expected December files (2015-2025) are present.")
else:
    print(f"Verification failed: {len(missing_files)} file(s) are missing.")
    print("Missing files:")
    for f in sorted(list(missing_files)):
        print(f"- {f}")

if present_files:
    print(f"\n{len(present_files)} file(s) are present:")
    for f in sorted(list(present_files)):
        print(f"- {f}")

"""## Final Task

### Subtask:
Summarize the verification of the downloaded and existing December files, confirming their presence and adherence to the naming convention.

## Summary:

### Q&A
The verification of the downloaded and existing December files confirmed that out of 11 expected files for the years 2015-2025, only 4 were present in the `/content/drive/MyDrive/FUNPUBLICOS/` directory. All found files adhered to the `funpub_YYYY_12.csv` naming convention.

### Data Analysis Key Findings
*   A total of 11 December files were expected for the years 2015 through 2025, following the `funpub_YYYY_12.csv` naming convention.
*   Only 4 files were found in the specified directory: `funpub_2015_12.csv`, `funpub_2016_12.csv`, `funpub_2022_12.csv`, and `funpub_2025_12.csv`.
*   7 files were identified as missing from the directory, including `funpub_2017_12.csv`, `funpub_2018_12.csv`, `funpub_2019_12.csv`, `funpub_2020_12.csv`, `funpub_2021_12.csv`, `funpub_2023_12.csv`, and `funpub_2024_12.csv`.

### Insights or Next Steps
*   Investigate why 7 of the expected December files are missing and proceed to download or locate them to ensure data completeness for the analysis.
*   Implement a more robust verification step post-download to immediately identify and report any missing files, preventing discrepancies in the dataset.

### Listar Variables del Archivo `funpub_2025_12.csv`

**Subtarea:** Cargar el archivo CSV de diciembre de 2025 y mostrar sus columnas para identificar las variables presentes.
"""

import polars as pl
import os

# Define the path to the funpub_2025_12.csv file
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
file_path = os.path.join(output_dir, 'funpub_2025_12.csv')

print(f"Cargando el archivo: {file_path}")

try:
    # Load the CSV file into a Polars DataFrame
    # Using separator=',' and encoding='latin1' as inferred from previous tasks
    # Added schema_overrides to correctly parse 'lugar' and other potential problematic columns as strings
    df_2025 = pl.read_csv(
        file_path,
        separator=',',
        encoding='latin1',
        schema_overrides={'lugar': pl.String, 'documento': pl.String, 'codigoPersona': pl.String}
    )

    print("Columnas presentes en funpub_2025_12.csv:")
    for col in df_2025.columns:
        print(f"- {col}")

except FileNotFoundError:
    print(f"Error: El archivo no fue encontrado en '{file_path}'.")
except pl.exceptions.ComputeError as e:
    print(f"Error al leer el archivo CSV: {e}. Puede que la separación, codificación o el esquema sean incorrectos.")
except Exception as e:
    print(f"Ocurrió un error inesperado: {e}")

"""# Task
## Create Mapping Table for Nivel

### Subtask:
Extract the 'nivel' and 'descripcion_nivel' columns from the `df_2025` DataFrame, obtain the unique combinations, and display the first few rows of the resulting mapping table. This table will be used to map level codes to their descriptions.

## Create Mapping Table for Nivel

### Subtask:
Extract the 'nivel' and 'descripcion_nivel' columns from the `df_2025` DataFrame, obtain the unique combinations, and display the first few rows of the resulting mapping table. This table will be used to map level codes to their descriptions.

**Reasoning**:
To create the mapping table, I will select the 'nivel' and 'descripcion_nivel' columns from `df_2025`, get their unique combinations, and store them in a new Polars DataFrame. Then, I'll display the first few rows of this mapping table.
"""

nivel_mapping_df = df_2025.select(['nivel', 'descripcion_nivel']).unique()

print("Mapping table for 'nivel' and 'descripcion_nivel':")
print(nivel_mapping_df.head())

"""## Save Mapping Table for Nivel

### Subtask:
Guardar la tabla de mapeo de 'nivel' en un archivo CSV (nivel_mapping.csv) en el directorio /content/drive/MyDrive/FUNPUBLICOS/ para su uso posterior en la compilación de datos.

**Reasoning**:
I need to save the `nivel_mapping_df` to a CSV file in the specified directory. I will use `os.path.join` to construct the full file path and the `to_csv` method of the Polars DataFrame to save it.
"""

import os

# 1. Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
os.makedirs(output_dir, exist_ok=True)

# 2. Define the output file path for the mapping table
output_file_path = os.path.join(output_dir, 'nivel_mapping.csv')

# 3. Save the nivel_mapping_df Polars DataFrame to a CSV file
nivel_mapping_df.write_csv(output_file_path, include_header=True, separator=',')

print(f"Mapping table for 'nivel' saved to: {output_file_path}")

"""## Create Mapping Table for Entidad

### Subtask:
Extract the 'entidad' and 'descripcion_entidad' columns from the `df_2025` DataFrame, obtain the unique combinations, and display the first few rows of the resulting mapping table. This table will be used to map entity codes to their descriptions.

**Reasoning**:
To create the mapping table, I will select the 'entidad' and 'descripcion_entidad' columns from `df_2025`, get their unique combinations, and store them in a new Polars DataFrame. Then, I'll display the first few rows of this mapping table.
"""

entidad_mapping_df = df_2025.select(['entidad', 'descripcion_entidad']).unique()

print("Mapping table for 'entidad' and 'descripcion_entidad':")
print(entidad_mapping_df.head())

"""**Reasoning**:
To save the mapping table, I will define the output directory and file path, then use the `write_csv` method of the Polars DataFrame to save `entidad_mapping_df` to a CSV file.


"""

import os

# 1. Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
os.makedirs(output_dir, exist_ok=True)

# 2. Define the output file path for the mapping table
output_file_path = os.path.join(output_dir, 'entidad_mapping.csv')

# 3. Save the entidad_mapping_df Polars DataFrame to a CSV file
entidad_mapping_df.write_csv(output_file_path, include_header=True, separator=',')

print(f"Mapping table for 'entidad' saved to: {output_file_path}")

"""## Create Mapping Table for OEE

### Subtask:
Extract the 'oee' and 'descripcion_oee' columns from the `df_2025` DataFrame, obtain the unique combinations, and display the first few rows of the resulting mapping table. This table will be used to map OEE codes to their descriptions.

**Reasoning**:
To create the OEE mapping table, I will select the 'oee' and 'descripcion_oee' columns from `df_2025`, get their unique combinations, and store them in a new Polars DataFrame. Then, I'll display the first few rows of this mapping table.
"""

oee_mapping_df = df_2025.select(['oee', 'descripcion_oee']).unique()

print("Mapping table for 'oee' and 'descripcion_oee':")
print(oee_mapping_df.head())

"""**Reasoning**:
To ensure the `oee_mapping_df` is persistent and available for future use, I will save it to a CSV file in the designated output directory.


"""

import os

# 1. Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
os.makedirs(output_dir, exist_ok=True)

# 2. Define the output file path for the mapping table
output_file_path = os.path.join(output_dir, 'oee_mapping.csv')

# 3. Save the oee_mapping_df Polars DataFrame to a CSV file
oee_mapping_df.write_csv(output_file_path, include_header=True, separator=',')

print(f"Mapping table for 'oee' saved to: {output_file_path}")

"""## Create Mapping Table for Objeto Gasto

### Subtask:
Extract the 'objeto_gasto' and 'concepto' columns from the `df_2025` DataFrame, obtain the unique combinations, and display the first few rows of the resulting mapping table. This table will be used to map object of expenditure codes to their concepts.

**Reasoning**:
To create the mapping table, I will select the 'objeto_gasto' and 'concepto' columns from `df_2025`, get their unique combinations, and store them in a new Polars DataFrame. Then, I'll display the first few rows of this mapping table.
"""

objeto_gasto_mapping_df = df_2025.select(['objeto_gasto', 'concepto']).unique()

print("Mapping table for 'objeto_gasto' and 'concepto':")
print(objeto_gasto_mapping_df.head())

"""**Reasoning**:
To persist the `objeto_gasto_mapping_df` for future use, I will save it to a CSV file in the specified output directory.


"""

import os

# 1. Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
os.makedirs(output_dir, exist_ok=True)

# 2. Define the output file path for the mapping table
output_file_path = os.path.join(output_dir, 'objeto_gasto_mapping.csv')

# 3. Save the objeto_gasto_mapping_df Polars DataFrame to a CSV file
objeto_gasto_mapping_df.write_csv(output_file_path, include_header=True, separator=',')

print(f"Mapping table for 'objeto_gasto' saved to: {output_file_path}")

"""## Final Task

### Subtask:
Summarize the creation and saving of the mapping tables for code and description columns, explaining how these tables will help reduce the compiled database size and facilitate data analysis across all years.

## Summary:

### Q&A
The mapping tables for code and description columns (`nivel`, `entidad`, `oee`, `objeto_gasto`) were created by extracting unique code-description pairs from the `df_2025` DataFrame. These tables were then saved as CSV files. These mapping tables will help reduce the compiled database size by allowing the storage of only numerical codes in the main datasets, instead of repetitive descriptive text. This approach also facilitates data analysis across all years by ensuring consistent descriptions for each code, simplifying data joins and standardization across different datasets.

### Data Analysis Key Findings
*   Four distinct mapping tables were successfully created and saved:
    *   `nivel_mapping_df`: Contains unique combinations of 'nivel' (e.g., 12, 24) and 'descripcion_nivel' (e.g., PODER EJECUTIVO, ENTIDADES PUBLICAS DE SEGURIDAD...).
    *   `entidad_mapping_df`: Stores unique pairs of 'entidad' and 'descripcion_entidad'.
    *   `oee_mapping_df`: Maps unique 'oee' codes to their 'descripcion_oee'.
    *   `objeto_gasto_mapping_df`: Links unique 'objeto\_gasto' codes to their 'concepto' descriptions.
*   Each mapping table was generated by selecting the relevant code and description columns from `df_2025` and extracting only the unique combinations.
*   All generated mapping tables were saved as CSV files (`nivel_mapping.csv`, `entidad_mapping.csv`, `oee_mapping.csv`, `objeto_gasto_mapping.csv`) in the `/content/drive/MyDrive/FUNPUBLICOS/` directory, ensuring their persistent storage for future use.

### Insights or Next Steps
*   These mapping tables provide a standardized reference for code-description pairs, which can be used to denormalize larger datasets, replacing verbose descriptions with efficient numerical codes, thereby optimizing storage and improving query performance.
*   The next step involves leveraging these mapping tables to process and compile the data from all years. This will enable consistent data cleaning, standardization, and efficient joining of data across different annual datasets using the established codes.

# Task
Compile all `funpub_YYYY_12.csv` files from 2015 to 2025 located in `/content/drive/MyDrive/FUNPUBLICOS/` into a single Polars DataFrame named `funpub_compilado_2015a2025.csv` in the same directory. The compilation should only include specific code columns and other relevant data fields, explicitly excluding descriptive columns like `descripcion_nivel`, `descripcion_entidad`, `descripcion_oee`, and `concepto`, while ensuring `schema_overrides` for `lugar`, `documento`, and `codigoPersona` are applied during loading. Finally, verify the compiled file by loading a small sample and displaying its head and column names, and summarize the process, including the columns included and excluded, and the benefits for data analysis and storage.

## Define Columns for Compilation

### Subtask:
Identify and define the list of columns to be included in the compiled dataset, excluding descriptive columns.

**Reasoning**:
I need to define a Python list `columns_to_include` based on the specified columns from the `df_2025` DataFrame, ensuring to exclude the descriptive columns as per the instructions. This list will be used in subsequent steps for data compilation.
"""

columns_to_include = [
    'anho',
    'mes',
    'nivel',
    'entidad',
    'oee',
    'documento',
    'nombres',
    'apellidos',
    'funcion',
    'estado',
    'carga_horaria',
    'anho_ingreso',
    'sexo',
    'discapacidad',
    'tipo_discapacidad',
    'fuente_financiamiento',
    'objeto_gasto',
    'linea',
    'categoria',
    'cargo',
    'presupuestado',
    'devengado',
    'movimiento',
    'lugar',
    'fecha_nacimiento',
    'fec_ult_modif',
    'uri',
    'fecha_acto',
    'correo',
    'profesion',
    'motivo_movimiento'
]

print(f"Defined {len(columns_to_include)} columns to include in the compiled dataset.")
print("Columns:", columns_to_include)

"""**Reasoning**:
Now that the list of columns to include is defined, I will iterate through the years 2015 to 2025, load each December CSV file, select only the specified columns, apply the necessary schema overrides, and concatenate them into a single Polars DataFrame. Finally, I will save this compiled DataFrame to a new CSV file.


"""

import polars as pl
import os

# Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'

# Define the schema overrides for problematic columns
schema_overrides = {'lugar': pl.String, 'documento': pl.String, 'codigoPersona': pl.String}

# Initialize an empty list to store DataFrames
df_list = []

# Iterate through the years from 2015 to 2025
for year in range(2015, 2026): # 2025 is inclusive
    file_path = os.path.join(output_dir, f'funpub_{year}_12.csv')

    if os.path.exists(file_path):
        print(f"Loading {file_path}...")
        try:
            # Load the CSV file, select only the specified columns, and apply schema overrides
            df = pl.read_csv(
                file_path,
                separator=',',
                encoding='latin1',
                schema_overrides=schema_overrides,
                columns=columns_to_include # Select only the defined columns
            )
            df_list.append(df)
            print(f"Successfully loaded {file_path} with {df.shape[0]} rows and {df.shape[1]} columns.")
        except pl.exceptions.ComputeError as e:
            print(f"Error reading {file_path}: {e}. Skipping this file.")
        except Exception as e:
            print(f"An unexpected error occurred while processing {file_path}: {e}. Skipping this file.")
    else:
        print(f"Warning: File not found: {file_path}. Skipping this file.")

# Concatenate all DataFrames in the list into a single DataFrame
if df_list:
    funpub_compilado_df = pl.concat(df_list)
    print(f"\nSuccessfully compiled {len(df_list)} files into a single DataFrame with {funpub_compilado_df.shape[0]} rows and {funpub_compilado_df.shape[1]} columns.")

    # Define the output path for the compiled CSV
    compiled_output_path = os.path.join(output_dir, 'funpub_compilado_2015a2025.csv')

    # Save the compiled DataFrame to a CSV file
    funpub_compilado_df.write_csv(compiled_output_path, include_header=True, separator=',')
    print(f"Compiled DataFrame saved to: {compiled_output_path}")

    # Verify the compiled file by loading a small sample and displaying its head and column names
    print("\nVerifying compiled file...")
    verified_df = pl.read_csv(
        compiled_output_path,
        separator=',',
        encoding='latin1',
        schema_overrides=schema_overrides,
        n_rows=5 # Load only a few rows for verification
    )
    print("First 5 rows of the compiled file:")
    print(verified_df.head())
    print("\nColumns in the compiled file:")
    for col in verified_df.columns:
        print(f"- {col}")
else:
    print("No files were successfully loaded and compiled.")

"""**Reasoning**:
The previous attempt to compile files failed due to inconsistent column names and data types across different years, specifically for `funpub_2015_12.csv` and files from 2017-2024. I need to implement a more robust loading process that handles these schema differences. This involves: 1) Defining specific `schema_overrides` and `null_values` for `funpub_2015_12.csv` to address the 'SIN LÍNEA' parsing error in the 'linea' column. 2) Creating a `column_rename_map` to standardize column names from the old schema (2017-2024) to the new schema (2016, 2025). 3) Loading all columns initially, then applying renaming for old schema files. 4) Selecting only the `columns_to_include` list, ensuring that any columns missing from a specific file after renaming are filled with nulls, and explicitly converting `anho_ingreso` to an integer type after extracting the year from potential date strings to maintain a consistent schema across all datasets.


"""

import polars as pl
import os

# Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'

# Define the target schema for `columns_to_include` data types for better consistency
# These are the dtypes expected for the final compiled DataFrame
target_schema = {
    'anho': pl.Int64,
    'mes': pl.Int64,
    'nivel': pl.Int64,
    'entidad': pl.Int64,
    'oee': pl.Int64,
    'documento': pl.String,
    'nombres': pl.String,
    'apellidos': pl.String,
    'funcion': pl.String,
    'estado': pl.String,
    'carga_horaria': pl.Int64,
    'anho_ingreso': pl.Int64,
    'sexo': pl.String,
    'discapacidad': pl.String,
    'tipo_discapacidad': pl.String,
    'fuente_financiamiento': pl.Int64,
    'objeto_gasto': pl.Int64,
    'linea': pl.String, # Keep as string due to 'SIN LÍNEA' and other potential non-numeric values
    'categoria': pl.String,
    'cargo': pl.String,
    'presupuestado': pl.Float64, # Assuming monetary values
    'devengado': pl.Float64,     # Assuming monetary values
    'movimiento': pl.String,
    'lugar': pl.String,
    'fecha_nacimiento': pl.String, # Keep as string for now to avoid parsing issues
    'fec_ult_modif': pl.String,
    'uri': pl.String,
    'fecha_acto': pl.String,
    'correo': pl.String,
    'profesion': pl.String,
    'motivo_movimiento': pl.String
}

# Ensure `columns_to_include` matches the keys of `target_schema`
columns_to_include = list(target_schema.keys())

# Define column rename map for older files (e.g., 2017-2024 as per error messages)
# Mappings are from their original names to the names in `columns_to_include`
column_rename_map = {
    'anio': 'anho',
    'codigoNivel': 'nivel',
    'codigoEntidad': 'entidad',
    'codigoPrograma': 'oee', # Assuming 'codigoPrograma' maps to 'oee'
    'codigoObjetoGasto': 'objeto_gasto',
    'codigoPersona': 'documento',
    'horasCatedra': 'carga_horaria',
    'codigoCategoria': 'categoria',
    'montoPresupuestado': 'presupuestado',
    'montoDevengado': 'devengado',
    'fechaIngreso': 'anho_ingreso' # Will extract year from this if it's a date string
}

# Initialize an empty list to store DataFrames
df_list = []

# Iterate through the years from 2015 to 2025
for year in range(2015, 2026): # 2025 is inclusive
    file_path = os.path.join(output_dir, f'funpub_{year}_12.csv')

    if os.path.exists(file_path):
        print(f"Loading {file_path}...")
        try:
            # Define schema overrides specific to reading, including potentially problematic columns
            # 'lugar' and 'documento' are always read as string
            # 'linea' is read as string to handle 'SIN LÍNEA' in 2015 and other non-numeric values
            read_schema_overrides = {
                'lugar': pl.String,
                'documento': pl.String,
                'linea': pl.String, # Force linea to string for robust parsing
                'codigoPersona': pl.String # For older schemas if it exists before renaming
            }
            # Null values for 2015 file specific issue
            null_values_for_file = ['SIN LÍNEA'] if year == 2015 else None

            # Load the CSV file. Do not use 'columns' arg yet to allow renaming.
            # try_parse_dates=True for 'fechaIngreso' (older schema) or other date columns.
            df = pl.read_csv(
                file_path,
                separator=',',
                encoding='latin1',
                schema_overrides=read_schema_overrides,
                null_values=null_values_for_file,
                try_parse_dates=True # Important for 'fechaIngreso' and similar
            )

            # Apply column renaming if it's an old schema file
            if year >= 2017 and year <= 2024: # Assuming these years use the old schema as per error
                df = df.rename(column_rename_map)

            # Process 'anho_ingreso' / 'fechaIngreso'
            if 'anho_ingreso' in df.columns:
                # Convert 'anho_ingreso' to integer, handling potential date strings or errors
                df = df.with_columns(
                    pl.col('anho_ingreso').cast(pl.String)
                    .str.extract(r'^(\d{4})').cast(pl.Int64, strict=False)
                    .alias('anho_ingreso')
                )

            # Select only the `columns_to_include` and ensure target schema types
            # If a column is not present, add it as a null column with the target type
            final_df_cols = []
            for col_name, col_dtype in target_schema.items():
                if col_name in df.columns:
                    final_df_cols.append(pl.col(col_name).cast(col_dtype, strict=False))
                else:
                    final_df_cols.append(pl.lit(None, dtype=col_dtype).alias(col_name))

            df = df.select(final_df_cols)

            df_list.append(df)
            print(f"Successfully loaded and processed {file_path} with {df.shape[0]} rows and {df.shape[1]} columns.")

        except pl.exceptions.ComputeError as e:
            print(f"Error reading or processing {file_path}: {e}. Skipping this file.")
        except Exception as e:
            print(f"An unexpected error occurred while processing {file_path}: {e}. Skipping this file.")
    else:
        print(f"Warning: File not found: {file_path}. Skipping this file.")

# Concatenate all DataFrames in the list into a single DataFrame
if df_list:
    funpub_compilado_df = pl.concat(df_list, how='vertical_relaxed') # Use vertical_relaxed to handle schema differences flexibly
    print(f"\nSuccessfully compiled {len(df_list)} files into a single DataFrame with {funpub_compilado_df.shape[0]} rows and {funpub_compilado_df.shape[1]} columns.")

    # Define the output path for the compiled CSV
    compiled_output_path = os.path.join(output_dir, 'funpub_compilado_2015a2025.csv')

    # Save the compiled DataFrame to a CSV file
    funpub_compilado_df.write_csv(compiled_output_path, include_header=True, separator=',')
    print(f"Compiled DataFrame saved to: {compiled_output_path}")

    # Verify the compiled file by loading a small sample and displaying its head and column names
    print("\nVerifying compiled file...")
    # Use the same schema_overrides for verification to ensure consistency
    verified_df = pl.read_csv(
        compiled_output_path,
        separator=',',
        encoding='latin1',
        schema_overrides=read_schema_overrides,
        n_rows=5 # Load only a few rows for verification
    )
    print("First 5 rows of the compiled file:")
    print(verified_df.head())
    print("\nColumns in the compiled file:")
    for col in verified_df.columns:
        print(f"- {col}")
else:
    print("No files were successfully loaded and compiled.")

"""**Reasoning**:
The previous code failed to process `funpub_2025_12.csv` due to a date parsing error in the `fecha_acto` column, even though it was defined as a string in `target_schema`. This is likely because `try_parse_dates=True` overrides the string type for columns that resemble dates. To fix this, I need to explicitly add `fecha_acto: pl.String` to the `read_schema_overrides` to ensure it's always read as a string, regardless of `try_parse_dates` attempting to infer date types.


"""

import polars as pl
import os

# Define the output directory
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'

# Define the target schema for `columns_to_include` data types for better consistency
# These are the dtypes expected for the final compiled DataFrame
target_schema = {
    'anho': pl.Int64,
    'mes': pl.Int64,
    'nivel': pl.Int64,
    'entidad': pl.Int64,
    'oee': pl.Int64,
    'documento': pl.String,
    'nombres': pl.String,
    'apellidos': pl.String,
    'funcion': pl.String,
    'estado': pl.String,
    'carga_horaria': pl.Int64,
    'anho_ingreso': pl.Int64,
    'sexo': pl.String,
    'discapacidad': pl.String,
    'tipo_discapacidad': pl.String,
    'fuente_financiamiento': pl.Int64,
    'objeto_gasto': pl.Int64,
    'linea': pl.String, # Keep as string due to 'SIN LÍNEA' and other potential non-numeric values
    'categoria': pl.String,
    'cargo': pl.String,
    'presupuestado': pl.Float64, # Assuming monetary values
    'devengado': pl.Float64,     # Assuming monetary values
    'movimiento': pl.String,
    'lugar': pl.String,
    'fecha_nacimiento': pl.String, # Keep as string for now to avoid parsing issues
    'fec_ult_modif': pl.String,
    'uri': pl.String,
    'fecha_acto': pl.String,
    'correo': pl.String,
    'profesion': pl.String,
    'motivo_movimiento': pl.String
}

# Ensure `columns_to_include` matches the keys of `target_schema`
columns_to_include = list(target_schema.keys())

# Define column rename map for older files (e.g., 2017-2024 as per error messages)
# Mappings are from their original names to the names in `columns_to_include`
column_rename_map = {
    'anio': 'anho',
    'codigoNivel': 'nivel',
    'codigoEntidad': 'entidad',
    'codigoPrograma': 'oee', # Assuming 'codigoPrograma' maps to 'oee'
    'codigoObjetoGasto': 'objeto_gasto',
    'codigoPersona': 'documento',
    'horasCatedra': 'carga_horaria',
    'codigoCategoria': 'categoria',
    'montoPresupuestado': 'presupuestado',
    'montoDevengado': 'devengado',
    'fechaIngreso': 'anho_ingreso' # Will extract year from this if it's a date string
}

# Initialize an empty list to store DataFrames
df_list = []

# Iterate through the years from 2015 to 2025
for year in range(2015, 2026): # 2025 is inclusive
    file_path = os.path.join(output_dir, f'funpub_{year}_12.csv')

    if os.path.exists(file_path):
        print(f"Loading {file_path}...")
        try:
            # Define schema overrides specific to reading, including potentially problematic columns
            # 'lugar' and 'documento' are always read as string
            # 'linea' is read as string to handle 'SIN LÍNEA' in 2015 and other non-numeric values
            read_schema_overrides = {
                'lugar': pl.String,
                'documento': pl.String,
                'linea': pl.String, # Force linea to string for robust parsing
                'codigoPersona': pl.String, # For older schemas if it exists before renaming
                'fecha_acto': pl.String # Explicitly cast fecha_acto to String to prevent parsing errors
            }
            # Null values for 2015 file specific issue
            null_values_for_file = ['SIN LÍNEA'] if year == 2015 else None

            # Load the CSV file. Do not use 'columns' arg yet to allow renaming.
            # try_parse_dates=True for 'fechaIngreso' (older schema) or other date columns.
            df = pl.read_csv(
                file_path,
                separator=',',
                encoding='latin1',
                schema_overrides=read_schema_overrides,
                null_values=null_values_for_file,
                try_parse_dates=True # Important for 'fechaIngreso' and similar
            )

            # Apply column renaming if it's an old schema file
            if year >= 2017 and year <= 2024: # Assuming these years use the old schema as per error
                df = df.rename(column_rename_map)

            # Process 'anho_ingreso' / 'fechaIngreso'
            if 'anho_ingreso' in df.columns:
                # Convert 'anho_ingreso' to integer, handling potential date strings or errors
                df = df.with_columns(
                    pl.col('anho_ingreso').cast(pl.String)
                    .str.extract(r'^(\d{4})').cast(pl.Int64, strict=False)
                    .alias('anho_ingreso')
                )

            # Select only the `columns_to_include` and ensure target schema types
            # If a column is not present, add it as a null column with the target type
            final_df_cols = []
            for col_name, col_dtype in target_schema.items():
                if col_name in df.columns:
                    final_df_cols.append(pl.col(col_name).cast(col_dtype, strict=False))
                else:
                    final_df_cols.append(pl.lit(None, dtype=col_dtype).alias(col_name))

            df = df.select(final_df_cols)

            df_list.append(df)
            print(f"Successfully loaded and processed {file_path} with {df.shape[0]} rows and {df.shape[1]} columns.")

        except pl.exceptions.ComputeError as e:
            print(f"Error reading or processing {file_path}: {e}. Skipping this file.")
        except Exception as e:
            print(f"An unexpected error occurred while processing {file_path}: {e}. Skipping this file.")
    else:
        print(f"Warning: File not found: {file_path}. Skipping this file.")

# Concatenate all DataFrames in the list into a single DataFrame
if df_list:
    funpub_compilado_df = pl.concat(df_list, how='vertical_relaxed') # Use vertical_relaxed to handle schema differences flexibly
    print(f"\nSuccessfully compiled {len(df_list)} files into a single DataFrame with {funpub_compilado_df.shape[0]} rows and {funpub_compilado_df.shape[1]} columns.")

    # Define the output path for the compiled CSV
    compiled_output_path = os.path.join(output_dir, 'funpub_compilado_2015a2025.csv')

    # Save the compiled DataFrame to a CSV file
    funpub_compilado_df.write_csv(compiled_output_path, include_header=True, separator=',')
    print(f"Compiled DataFrame saved to: {compiled_output_path}")

    # Verify the compiled file by loading a small sample and displaying its head and column names
    print("\nVerifying compiled file...")
    # Use the same schema_overrides for verification to ensure consistency
    verified_df = pl.read_csv(
        compiled_output_path,
        separator=',',
        encoding='latin1',
        schema_overrides=read_schema_overrides,
        n_rows=5 # Load only a few rows for verification
    )
    print("First 5 rows of the compiled file:")
    print(verified_df.head())
    print("\nColumns in the compiled file:")
    for col in verified_df.columns:
        print(f"- {col}")
else:
    print("No files were successfully loaded and compiled.")

"""## Final Task

### Subtask:
Summarize the process of compiling the annual data into a single file, detailing the columns included and excluded, and explaining the benefits of this approach for data analysis and storage optimization.

## Summary:

### Q&A
The process of compiling the annual `funpub_YYYY_12.csv` files from 2015 to 2025 involved several steps to address data inconsistencies and optimize the dataset for analysis. Each annual file was iteratively loaded using Polars, applying specific schema overrides for problematic columns like `lugar`, `documento`, and `codigoPersona` to ensure they were read as strings. Column names for files from 2017 to 2024 were standardized using a renaming map to match the target schema. Data types were explicitly cast according to a predefined `target_schema`, and specific handling was implemented for `anho_ingreso` to extract the year and for the `linea` column in the 2015 file to treat 'SIN LÍNEA' as a null value. After individual processing, all DataFrames were vertically concatenated into a single DataFrame, which was then saved as `funpub_compilado_2015a2025.csv`.

**Columns Included:** The compiled dataset includes 31 columns: `anho`, `mes`, `nivel`, `entidad`, `oee`, `documento`, `nombres`, `apellidos`, `funcion`, `estado`, `carga_horaria`, `anho_ingreso`, `sexo`, `discapacidad`, `tipo_discapacidad`, `fuente_financiamiento`, `objeto_gasto`, `linea`, `categoria`, `cargo`, `presupuestado`, `devengado`, `movimiento`, `lugar`, `fecha_nacimiento`, `fec_ult_modif`, `uri`, `fecha_acto`, `correo`, `profesion`, and `motivo_movimiento`.

**Columns Excluded:** Descriptive columns such as `descripcion_nivel`, `descripcion_entidad`, `descripcion_oee`, and `concepto` were explicitly excluded.

**Benefits for Data Analysis and Storage Optimization:**
*   **Consistency:** The compilation results in a unified dataset with a consistent schema and data types across all years, simplifying cross-year analysis.
*   **Efficiency:** By excluding verbose descriptive columns and focusing on core identifiers and measurable data, the dataset size is significantly reduced, leading to lower storage requirements and faster query performance for analytical tasks.
*   **Focused Analysis:** Analysts can work with a streamlined dataset, concentrating on essential data fields without the distraction or overhead of less critical information.
*   **Performance:** Utilizing Polars ensures that the handling of large datasets remains highly performant during loading, processing, and subsequent querying.

### Data Analysis Key Findings
*   The compilation successfully merged 11 annual files from 2015 to 2025 into a single Polars DataFrame, `funpub_compilado_2015a2025.csv`.
*   The final compiled dataset contains 11,524,792 rows and 31 columns.
*   Significant data quality and schema inconsistencies were identified across the annual files:
    *   The `linea` column in `funpub_2015_12.csv` contained non-numeric values ('SIN LÍNEA'), requiring specific null value handling.
    *   Files from 2017 to 2024 used inconsistent column naming (e.g., `anio` instead of `anho`), necessitating a column renaming map.
    *   A date parsing error in `fecha_acto` was observed in `funpub_2025_12.csv` due to an invalid date string, which was resolved by explicitly casting the column to `pl.String` during loading.
*   The process involved defining a strict target schema and applying dynamic schema overrides and column renames to accommodate these variations.

### Insights or Next Steps
*   The compiled and harmonized dataset provides a robust foundation for longitudinal analysis of public sector employee data, allowing for direct comparisons and aggregation across more than a decade.
*   Implementing automated data validation and standardization checks at the source or during the initial ingestion phase could prevent future data quality issues and streamline the compilation process further.

# Task
Load the `funpub_compilado_2015a2025.csv` file from `/content/drive/MyDrive/FUNPUBLICOS/` into a Polars DataFrame and verify its content by displaying the first few rows and its schema.

## Load Compiled CSV

### Subtask:
Load the `funpub_compilado_2015a2025.csv` file into a Polars DataFrame.

**Reasoning**:
To load the `funpub_compilado_2015a2025.csv` file into a Polars DataFrame, I will use `polars.read_csv` with the specified file path, separator, encoding, and schema overrides.
"""

import polars as pl
import os

# 1. Define the output_dir variable
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'

# 2. Construct the full file path
compiled_file_path = os.path.join(output_dir, 'funpub_compilado_2015a2025.csv')

print(f"Attempting to load: {compiled_file_path}")

try:
    # 3. Load the CSV file into a Polars DataFrame
    # The read_schema_overrides dictionary is available from the previous execution context.
    funpub_df = pl.read_csv(
        compiled_file_path,
        separator=',',
        encoding='latin1',
        schema_overrides=read_schema_overrides # Use the schema overrides defined previously
    )
    print(f"Successfully loaded funpub_compilado_2015a2025.csv into funpub_df with {funpub_df.shape[0]} rows and {funpub_df.shape[1]} columns.")
    print("First 5 rows of funpub_df:")
    print(funpub_df.head())
    print("Columns in funpub_df:")
    for col in funpub_df.columns:
        print(f"- {col}")

except FileNotFoundError:
    print(f"Error: The compiled file was not found at '{compiled_file_path}'. Please ensure it was created correctly.")
except pl.exceptions.ComputeError as e:
    print(f"Error during CSV loading or parsing: {e}. Check file integrity, separator, encoding, or schema overrides.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""# Task
Re-define the `read_schema_overrides` dictionary within the current cell's scope and then load the `funpub_compilado_2015a2025.csv` file into a Polars DataFrame from `/content/drive/MyDrive/FUNPUBLICOS/`, ensuring proper schema handling. This step also includes displaying the first few rows and the schema for verification, and finally summarizing the successful loading and verification of the file, confirming its content and structure after resolving the loading error.

## Load Compiled CSV (Fixed)

### Subtask:
Re-define the `read_schema_overrides` dictionary within the current cell's scope and then load the `funpub_compilado_2015a2025.csv` file into a Polars DataFrame, ensuring proper schema handling. This step also includes displaying the first few rows and the schema for verification.

**Reasoning**:
The previous attempt to load the compiled CSV failed because `read_schema_overrides` was not defined in the current cell's scope. I will re-define this dictionary and then load the CSV, displaying its head and schema for verification as per the instructions.
"""

import polars as pl
import os

# 1. Define the output_dir variable
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'

# 2. Construct the full file path
compiled_file_path = os.path.join(output_dir, 'funpub_compilado_2015a2025.csv')

print(f"Attempting to load: {compiled_file_path}")

# 3. Re-define the read_schema_overrides dictionary
# These were determined necessary from previous compilation attempts.
read_schema_overrides = {
    'lugar': pl.String,
    'documento': pl.String,
    'linea': pl.String, # Force linea to string for robust parsing
    'codigoPersona': pl.String, # For older schemas if it exists before renaming
    'fecha_acto': pl.String # Explicitly cast fecha_acto to String to prevent parsing errors
}

try:
    # 4. Load the CSV file into a Polars DataFrame
    funpub_df = pl.read_csv(
        compiled_file_path,
        separator=',',
        encoding='latin1',
        schema_overrides=read_schema_overrides
    )
    print(f"Successfully loaded funpub_compilado_2015a2025.csv into funpub_df with {funpub_df.shape[0]} rows and {funpub_df.shape[1]} columns.")

    # 5. Display the first 5 rows of funpub_df
    print("\nFirst 5 rows of funpub_df:")
    print(funpub_df.head())

    # 6. Print all column names and their data types
    print("\nSchema of funpub_df:")
    for col_name, col_type in funpub_df.schema.items():
        print(f"- {col_name}: {col_type}")

except FileNotFoundError:
    print(f"Error: The compiled file was not found at '{compiled_file_path}'. Please ensure it was created correctly.")
except pl.exceptions.ComputeError as e:
    print(f"Error during CSV loading or parsing: {e}. Check file integrity, separator, encoding, or schema overrides.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""## Final Task

### Subtask:
Summarize the process of compiling the annual data into a single file, detailing the columns included and excluded, and explaining the benefits of this approach for data analysis and storage optimization.

## Summary:

### Q&A
The process of compiling the annual `funpub_YYYY_12.csv` files from 2015 to 2025 involved several steps to address data inconsistencies and optimize the dataset for analysis. Each annual file was iteratively loaded using Polars, applying specific schema overrides for problematic columns like `lugar`, `documento`, and `codigoPersona` to ensure they were read as strings. Column names for files from 2017 to 2024 were standardized using a renaming map to match the target schema. Data types were explicitly cast according to a predefined `target_schema`, and specific handling was implemented for `anho_ingreso` to extract the year and for the `linea` column in the 2015 file to treat 'SIN LÍNEA' as a null value. After individual processing, all DataFrames were vertically concatenated into a single DataFrame, which was then saved as `funpub_compilado_2015a2025.csv`.

**Columns Included:** The compiled dataset includes 31 columns: `anho`, `mes`, `nivel`, `entidad`, `oee`, `documento`, `nombres`, `apellidos`, `funcion`, `estado`, `carga_horaria`, `anho_ingreso`, `sexo`, `discapacidad`, `tipo_discapacidad`, `fuente_financiamiento`, `objeto_gasto`, `linea`, `categoria`, `cargo`, `presupuestado`, `devengado`, `movimiento`, `lugar`, `fecha_nacimiento`, `fec_ult_modif`, `uri`, `fecha_acto`, `correo`, `profesion`, and `motivo_movimiento`.

**Columns Excluded:** Descriptive columns such as `descripcion_nivel`, `descripcion_entidad`, `descripcion_oee`, and `concepto` were explicitly excluded.

**Benefits for Data Analysis and Storage Optimization:**
*   **Consistency:** The compilation results in a unified dataset with a consistent schema and data types across all years, simplifying cross-year analysis.
*   **Efficiency:** By excluding verbose descriptive columns and focusing on core identifiers and measurable data, the dataset size is significantly reduced, leading to lower storage requirements and faster query performance for analytical tasks.
*   **Focused Analysis:** Analysts can work with a streamlined dataset, concentrating on essential data fields without the distraction or overhead of less critical information.
*   **Performance:** Utilizing Polars ensures that the handling of large datasets remains highly performant during loading, processing, and subsequent querying.

### Data Analysis Key Findings
*   The compilation successfully merged 11 annual files from 2015 to 2025 into a single Polars DataFrame, `funpub_compilado_2015a2025.csv`.
*   The final compiled dataset contains 11,524,792 rows and 31 columns.
*   Significant data quality and schema inconsistencies were identified across the annual files:
    *   The `linea` column in `funpub_2015_12.csv` contained non-numeric values ('SIN LÍNEA'), requiring specific null value handling.
    *   Files from 2017 to 2024 used inconsistent column naming (e.g., `anio` instead of `anho`), necessitating a column renaming map.
    *   A date parsing error in `fecha_acto` was observed in `funpub_2025_12.csv` due to an invalid date string, which was resolved by explicitly casting the column to `pl.String` during loading.
*   The process involved defining a strict target schema and applying dynamic schema overrides and column renames to accommodate these variations.

### Insights or Next Steps
*   The compiled and harmonized dataset provides a robust foundation for longitudinal analysis of public sector employee data, allowing for direct comparisons and aggregation across more than a decade.
*   Implementing automated data validation and standardization checks at the source or during the initial ingestion phase could prevent future data quality issues and streamline the compilation process further.

## Summary:

### Q&A
The `funpub_compilado_2015a2025.csv` file, containing 11,524,792 rows and 31 columns, was successfully loaded into a Polars DataFrame named `funpub_df`. The previous loading error, which stemmed from `read_schema_overrides` not being defined in the current scope, was resolved by re-defining the dictionary within the cell. The explicit schema overrides for 'lugar', 'documento', 'linea', 'codigoPersona', and 'fecha_acto' ensured robust parsing of the CSV content.

### Data Analysis Key Findings
*   The compiled dataset, encompassing data from 2015 to 2025, is now available in `funpub_df` with a consistent schema.
*   The first 5 rows and the complete schema of the DataFrame were displayed, confirming the correct loading of data types for each column (e.g., `anho: Int64`, `documento: String`, `presupuestado: Float64`).
*   The resolution of the `read_schema_overrides` scope issue highlights the importance of explicitly defining necessary variables for each execution context in a notebook environment.

### Insights or Next Steps
*   The successfully loaded `funpub_df` is now ready for further data cleaning, transformation, and analysis. This includes potentially joining with the previously created mapping tables for `nivel`, `entidad`, `oee`, and `objeto_gasto` to add descriptive information as needed.
*   Further validation of data quality within `funpub_df`, such as checking for missing values, outliers, and data distribution, can now commence.

## Final Task

### Subtask:
Summarize the successful loading and verification of the `funpub_compilado_2015a2025.csv` file, confirming its content and structure after resolving the loading error.

## Summary:

### Q&A
The `funpub_compilado_2015a2025.csv` file was successfully loaded into a Polars DataFrame named `funpub_df` after re-defining the `read_schema_overrides` dictionary within the current cell's scope, which resolved a previous loading error. The file's content and structure were confirmed by displaying its first few rows and schema, ensuring proper handling of data types.

### Data Analysis Key Findings
*   The `funpub_compilado_2015a2025.csv` file was successfully loaded from `/content/drive/MyDrive/FUNPUBLICOS/` into a Polars DataFrame (`funpub_df`).
*   The loaded DataFrame contains 11,524,792 rows and 31 columns, indicating a substantial dataset.
*   The `read_schema_overrides` dictionary was correctly applied, ensuring specific columns such as 'lugar', 'documento', 'linea', 'codigoPersona', and 'fecha_acto' were explicitly cast as `String` types, which was crucial for robust parsing and error prevention.
*   Verification steps confirmed the correct schema, with data types like `anho` as `Int64`, `documento` as `String`, and `presupuestado` as `Float64` accurately reflected.

### Insights or Next Steps
*   The successfully loaded `funpub_df` is now prepared for subsequent data cleaning, transformation, and analytical tasks, potentially involving merges with previously generated mapping tables for descriptive information.
*   Further data quality checks, including identifying missing values, outliers, and examining data distributions, should be performed on the `funpub_df` to ensure its integrity and suitability for analysis.

# Task
Load the `nivel_mapping.csv` file from `/content/drive/MyDrive/FUNPUBLICOS/` into a Polars DataFrame, and then verify its content by displaying the first few rows and its schema.

## Load and Verify nivel_mapping.csv

### Subtask:
Load the `nivel_mapping.csv` file from the specified directory into a Polars DataFrame and display its first few rows and schema.

**Reasoning**:
To load the `nivel_mapping.csv` file, I will use `polars.read_csv` with the specified file path, separator, and encoding, then display the first few rows and the schema to verify its content and structure.
"""

import polars as pl
import os

# Define the directory path and filename
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
file_name = 'nivel_mapping.csv'

# Construct the full file path
file_path = os.path.join(output_dir, file_name)

print(f"Attempting to load: {file_path}")

try:
    # Load the CSV file into a Polars DataFrame
    # Using separator=',' and encoding='latin1' as inferred from previous tasks
    nivel_mapping_df = pl.read_csv(
        file_path,
        separator=',',
        encoding='latin1'
    )

    print(f"Successfully loaded {file_name} with {nivel_mapping_df.shape[0]} rows and {nivel_mapping_df.shape[1]} columns.")

    # Display the first 5 rows
    print("\nFirst 5 rows of nivel_mapping_df:")
    print(nivel_mapping_df.head())

    # Display the schema
    print("\nSchema of nivel_mapping_df:")
    for col_name, col_type in nivel_mapping_df.schema.items():
        print(f"- {col_name}: {col_type}")

except FileNotFoundError:
    print(f"Error: The file was not found at '{file_path}'. Please ensure it was created correctly.")
except pl.exceptions.ComputeError as e:
    print(f"Error during CSV loading or parsing: {e}. Check file integrity, separator, encoding, or schema.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""## Load and Verify entidad_mapping.csv

### Subtask:
Load the `entidad_mapping.csv` file from the specified directory into a Polars DataFrame and display its first few rows and schema.

**Reasoning**:
To load the `entidad_mapping.csv` file, I will use `polars.read_csv` with the specified file path, separator, and encoding, then display the first few rows and the schema to verify its content and structure.
"""

import polars as pl
import os

# Define the directory path and filename
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
file_name = 'entidad_mapping.csv'

# Construct the full file path
file_path = os.path.join(output_dir, file_name)

print(f"Attempting to load: {file_path}")

try:
    # Load the CSV file into a Polars DataFrame
    # Using separator=',' and encoding='latin1' as inferred from previous tasks
    entidad_mapping_df = pl.read_csv(
        file_path,
        separator=',',
        encoding='latin1'
    )

    print(f"Successfully loaded {file_name} with {entidad_mapping_df.shape[0]} rows and {entidad_mapping_df.shape[1]} columns.")

    # Display the first 5 rows
    print("\nFirst 5 rows of entidad_mapping_df:")
    print(entidad_mapping_df.head())

    # Display the schema
    print("\nSchema of entidad_mapping_df:")
    for col_name, col_type in entidad_mapping_df.schema.items():
        print(f"- {col_name}: {col_type}")

except FileNotFoundError:
    print(f"Error: The file was not found at '{file_path}'. Please ensure it was created correctly.")
except pl.exceptions.ComputeError as e:
    print(f"Error during CSV loading or parsing: {e}. Check file integrity, separator, encoding, or schema.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""**Reasoning**:
The current subtask requires loading and verifying the `oee_mapping.csv` file. I will use the same approach as for the previous mapping tables: load the CSV into a Polars DataFrame, then display its head and schema to confirm successful loading and structure.


"""

import polars as pl
import os

# Define the directory path and filename
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
file_name = 'oee_mapping.csv'

# Construct the full file path
file_path = os.path.join(output_dir, file_name)

print(f"Attempting to load: {file_path}")

try:
    # Load the CSV file into a Polars DataFrame
    # Using separator=',' and encoding='latin1' as inferred from previous tasks
    oee_mapping_df = pl.read_csv(
        file_path,
        separator=',',
        encoding='latin1'
    )

    print(f"Successfully loaded {file_name} with {oee_mapping_df.shape[0]} rows and {oee_mapping_df.shape[1]} columns.")

    # Display the first 5 rows
    print("\nFirst 5 rows of oee_mapping_df:")
    print(oee_mapping_df.head())

    # Display the schema
    print("\nSchema of oee_mapping_df:")
    for col_name, col_type in oee_mapping_df.schema.items():
        print(f"- {col_name}: {col_type}")

except FileNotFoundError:
    print(f"Error: The file was not found at '{file_path}'. Please ensure it was created correctly.")
except pl.exceptions.ComputeError as e:
    print(f"Error during CSV loading or parsing: {e}. Check file integrity, separator, encoding, or schema.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""**Reasoning**:
To load the `objeto_gasto_mapping.csv` file, I will use `polars.read_csv` with the specified file path, separator, and encoding, then display the first few rows and the schema to verify its content and structure.


"""

import polars as pl
import os

# Define the directory path and filename
output_dir = '/content/drive/MyDrive/FUNPUBLICOS/'
file_name = 'objeto_gasto_mapping.csv'

# Construct the full file path
file_path = os.path.join(output_dir, file_name)

print(f"Attempting to load: {file_path}")

try:
    # Load the CSV file into a Polars DataFrame
    # Using separator=',' and encoding='latin1' as inferred from previous tasks
    objeto_gasto_mapping_df = pl.read_csv(
        file_path,
        separator=',',
        encoding='latin1'
    )

    print(f"Successfully loaded {file_name} with {objeto_gasto_mapping_df.shape[0]} rows and {objeto_gasto_mapping_df.shape[1]} columns.")

    # Display the first 5 rows
    print("\nFirst 5 rows of objeto_gasto_mapping_df:")
    print(objeto_gasto_mapping_df.head())

    # Display the schema
    print("\nSchema of objeto_gasto_mapping_df:")
    for col_name, col_type in objeto_gasto_mapping_df.schema.items():
        print(f"- {col_name}: {col_type}")

except FileNotFoundError:
    print(f"Error: The file was not found at '{file_path}'. Please ensure it was created correctly.")
except pl.exceptions.ComputeError as e:
    print(f"Error during CSV loading or parsing: {e}. Check file integrity, separator, encoding, or schema.")
except Exception as e:
    print(f"An unexpected error occurred: {e}")

"""## Summary:

### Q&A
All four mapping tables (`nivel_mapping.csv`, `entidad_mapping.csv`, `oee_mapping.csv`, and `objeto_gasto_mapping.csv`) have been successfully loaded into Polars DataFrames and verified. Each loading step confirmed the correct number of rows and columns, as well as the expected schema for each DataFrame.

### Data Analysis Key Findings
*   `nivel_mapping_df`: Loaded with 14 rows and 2 columns, mapping 'nivel' (Int64) to 'descripcion_nivel' (String).
*   `entidad_mapping_df`: Loaded with 113 rows and 2 columns, mapping 'entidad' (Int64) to 'descripcion_entidad' (String).
*   `oee_mapping_df`: Loaded with 343 rows and 2 columns, mapping 'oee' (Int64) to 'descripcion_oee' (String).
*   `objeto_gasto_mapping_df`: Loaded with 4297 rows and 2 columns, mapping 'objeto_gasto' (Int64) to 'concepto' (String).
*   The use of `separator=','` and `encoding='latin1'` was consistent and successful across all mapping files.

### Insights or Next Steps
*   The successful loading and verification of these mapping tables ensure that descriptive information is readily available for joining with the main `funpub_compilado_2015a2025.csv` DataFrame. This will allow for enrichment of the compiled data with human-readable descriptions without inflating the size of the primary dataset.
*   These tables are crucial for subsequent data analysis, visualization, and reporting, providing clear definitions for the numerical codes in the main dataset.
*   The next logical step would be to join these mapping tables with the `funpub_df` to provide comprehensive descriptive attributes for the various codes present in the compiled dataset.

## Summarize Loading and Verification of Mapping Tables

### Subtask:
Summarize the successful loading and verification of all mapping tables (`nivel_mapping.csv`, `entidad_mapping.csv`, `oee_mapping.csv`, `objeto_gasto_mapping.csv`), confirming their content and structure.

## Summary: Loading and Verification of Mapping Tables

### Q&A
The four mapping tables, `nivel_mapping.csv`, `entidad_mapping.csv`, `oee_mapping.csv`, and `objeto_gasto_mapping.csv`, were successfully loaded into Polars DataFrames (`nivel_mapping_df`, `entidad_mapping_df`, `oee_mapping_df`, `objeto_gasto_mapping_df` respectively). Each loading process confirmed the file's presence, the number of rows and columns, and the correctness of their schemas, ensuring that the code and description columns were properly identified (e.g., `nivel: Int64`, `descripcion_nivel: String`).

### Data Analysis Key Findings
*   **`nivel_mapping_df`**: Loaded successfully with 14 rows and 2 columns. Schema verified as `nivel: Int64` and `descripcion_nivel: String`.
*   **`entidad_mapping_df`**: Loaded successfully with 113 rows and 2 columns. Schema verified as `entidad: Int64` and `descripcion_entidad: String`.
*   **`oee_mapping_df`**: Loaded successfully with 343 rows and 2 columns. Schema verified as `oee: Int64` and `descripcion_oee: String`.
*   **`objeto_gasto_mapping_df`**: Loaded successfully with 4,297 rows and 2 columns. Schema verified as `objeto_gasto: Int64` and `concepto: String`.

All tables showed a consistent structure with an integer code column and a string description column, as expected.

### Insights or Next Steps
The successfully loaded mapping tables are now ready for integration with the main compiled dataset (`funpub_compilado_2015a2025.csv`). These tables are crucial for enriching the compiled data by reintroducing descriptive information (e.g., converting 'nivel' codes back to 'descripcion_nivel' when needed for human-readable reports or dashboards). This approach keeps the main compiled dataset lean for efficient storage and computation, while allowing for on-demand data enrichment. They will facilitate clearer analysis, visualization, and interpretation of the public sector employee data by providing context to the numerical codes.

## Merge Nivel Mapping into Main DataFrame

### Subtask:
Merge the `nivel_mapping_df` with the `funpub_df` on the 'nivel' column to add the 'descripcion_nivel' to the main DataFrame.

**Reasoning**:
To merge the `nivel_mapping_df` with `funpub_df`, I will perform a left join on the 'nivel' column. This will add the 'descripcion_nivel' column to the main DataFrame. Afterward, I will display the first few rows and the schema of the updated `funpub_df` to verify the merge operation.
"""

funpub_df = funpub_df.join(
nivel_mapping_df,
on='nivel',
how='left'
)

print("First 5 rows of funpub_df after merging nivel_mapping_df:")
print(funpub_df.head())

print("\nSchema of funpub_df after merging nivel_mapping_df:")
for col_name, col_type in funpub_df.schema.items():
    print(f"- {col_name}: {col_type}")

"""**Reasoning**:
To merge the `entidad_mapping_df` with `funpub_df`, I will perform a left join on the 'entidad' column. This will add the 'descripcion_entidad' column to the main DataFrame. Afterward, I will display the first few rows and the schema of the updated `funpub_df` to verify the merge operation.


"""

funpub_df = funpub_df.join(
    entidad_mapping_df,
    on='entidad',
    how='left'
)

print("First 5 rows of funpub_df after merging entidad_mapping_df:")
print(funpub_df.head())

print("\nSchema of funpub_df after merging entidad_mapping_df:")
for col_name, col_type in funpub_df.schema.items():
    print(f"- {col_name}: {col_type}")

"""**Reasoning**:
The previous code block for merging `entidad_mapping_df` did not execute. I will re-run the same code block to perform the merge operation as intended, and then display the updated DataFrame's head and schema for verification.


"""

funpub_df = funpub_df.join(
    entidad_mapping_df,
    on='entidad',
    how='left'
)

print("First 5 rows of funpub_df after merging entidad_mapping_df:")
print(funpub_df.head())

print("\nSchema of funpub_df after merging entidad_mapping_df:")
for col_name, col_type in funpub_df.schema.items():
    print(f"- {col_name}: {col_type}")

"""**Reasoning**:
The previous cell failed because 'funpub_df' was not defined in the current execution scope. To fix this, I need to re-load 'funpub_df' from the compiled CSV file, re-define the necessary 'read_schema_overrides', and also re-load 'entidad_mapping_df' before performing the join operation. I will also re-import polars and os to ensure all dependencies are available.

**Reasoning**:
The subtask explicitly asks to merge `nivel_mapping_df` with `funpub_df`. Since `funpub_df` was just re-loaded in the previous step (without `descripcion_nivel`) and `nivel_mapping_df` might not be in the current execution scope, I will first re-load `nivel_mapping_df`. Then I will perform the left join operation between the reloaded `funpub_df` and `nivel_mapping_df` on the 'nivel' column. Finally, I will display the first few rows and the schema of the updated `funpub_df` to verify the merge.
"""